"""Create Country table

Revision ID: 27413609c6b2
Revises: 2174b4d5ffae
Create Date: 2025-10-27 12:33:57.384631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27413609c6b2'
down_revision: Union[str, Sequence[str], None] = '2174b4d5ffae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('capital', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('population', sa.BigInteger(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('estimated_gdp', sa.Numeric(precision=30, scale=1), nullable=True),
    sa.Column('flag_url', sa.String(length=40), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
