"""describe your change here

Revision ID: 567eacfabc49
Revises: 684b0e2defd0
Create Date: 2025-10-28 23:42:28.792882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567eacfabc49'
down_revision: Union[str, Sequence[str], None] = '684b0e2defd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('name'), table_name='countries')
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.create_index(op.f('name'), 'countries', ['name'], unique=True)
    # ### end Alembic commands ###
