"""Update datetime column

Revision ID: 684b0e2defd0
Revises: a3ed948a5faa
Create Date: 2025-10-27 18:51:13.821641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '684b0e2defd0'
down_revision: Union[str, Sequence[str], None] = 'a3ed948a5faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'last_refreshed_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'last_refreshed_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
