"""Altered gdp fiels

Revision ID: e541c5023597
Revises: 27413609c6b2
Create Date: 2025-10-27 16:10:26.213251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e541c5023597'
down_revision: Union[str, Sequence[str], None] = '27413609c6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'exchange_rate',
               existing_type=mysql.DECIMAL(precision=20, scale=2),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('countries', 'estimated_gdp',
               existing_type=mysql.DECIMAL(precision=30, scale=1),
               type_=sa.Double(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'estimated_gdp',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=30, scale=1),
               existing_nullable=True)
    op.alter_column('countries', 'exchange_rate',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=20, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
